package com.example.jdbcdemo.service;

import com.example.jdbcdemo.domain.Dog;

import java.sql.*;

public class DogService {

    private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTableDog = "CREATE TABLE Dog(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(30) UNIQUE, date_of_birth date, is_vaccinated boolean, weight double, sex varchar(1))";

    private Statement statement;

    public DogService(){
        try{
           connection = DriverManager.getConnection(url);
           statement = connection.createStatement();

            ResultSet resultSet = connection.getMetaData().getTables(null,null,null,null);
            boolean tableExists = false;
            while (resultSet.next()){
                if("Dog".equalsIgnoreCase(resultSet.getString("table_name"))){
                    tableExists = true;
                    break;
                }
            }
            if(!tableExists){
                statement.executeUpdate(createTableDog);
            }

        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    public void clearDog(){

    }

    public void addDog(Dog dog) throws SQLException {
        String addDogSql = "INSERT INTO Dog (name ,date_of_birth ,is_vaccinated, weight, sex) VALUES " +
                "(\'" + dog.getName() + "\' ,\'" + dog.getDateOfBirth() + "\' ," + dog.isVaccinated() + " ," + dog.getWeight() + " ,\'" + dog.getSex() + "\')";
        statement.executeUpdate(addDogSql);
    }

    public void deleteDog(Dog dog) throws SQLException {
        ResultSet resultSet = statement.executeQuery("SELECT id FROM Dog WHERE name="+dog.getName());
        String deleteDogSql = "DELETE FROM Dog WHERE id=";
        statement.executeUpdate(deleteDogSql);
    }


}
